### ISSUE TITLE
Implement smartcar birdseyeview

### ISSUE THREAD

**Issue by Gabri1998** [DIT113-V22/group-02#64]
As a user, I want to be able to view my car from above during parking, so that I can get information on obstacles  at all directions simultaneously.
 
Acceptance criteria: 

- [x] The Camera must show an overhead 360 degree view of itself and the environment around with view radius of around 2 meters.

**Comment by platisd** [comment]
How will you do this?!

**Comment by adityak714** [comment]
> How will you do this?!
> 
> I am referring to the 360 bird's eye view. 

Yes, a unique brain teaser and head-ache it might be, we are worried, but if possible, at least my interpretation was that maybe the stream that the camera gets, can be linked to a camera instance in the mod. 

In Godot, as different objects and nodes can be added, I was thinking a Camera node can be made just above the smartcar, sort of joined to it, looking at it from the top. Then the OV7... camera that Arduino operates, can somehow read frames by communicating with the POV of how that camera node is angled in the vehicle mod, instead of somewhere from the front of the car only. And then by reading those frames, it can be sent via MQTT into the Android app to be shown. I'll reach out to the TAs for clarification and their input on this can even be done in the first place, or not.

**Comment by platisd** [comment]
@AeroStun @RuthgerD

**Comment by RuthgerD** [comment]
This would not make a lot of sense in the real world... But it is indeed possible to have a floating camera looking down on the car :)

**Comment by sh4r10** [comment]
Perhaps the way we implement it might not make sense (obviously you dont have a camera flying over you at all times), but the end result most definitely makes sense as most modern cars using a combination of fish eye cameras can provide an overhead view for easier maneuvering in tight spaces. Hence, we think it is quite relevant.

**Comment by arrestoteles** [comment]
@adityak714 @Gabri1998 I would say we remove this feature and focus on frontcam - what do you think?
